---
title: "Homework 15"
format: html
---
## Setting Things Up

```{r}
rm(list = ls())
library(here)
library(tidyverse)
```

```{r}
compensation_df<- read.csv(here("Data", "compensation.csv"))
compensation_df
```

## Intro to summary()
```{r}
glimpse(compensation_df)
summary(compensation_df)
```

## Intro to dyplr

### Select()
```{r}
select(compensation_df, Fruit) #select a specific column
select(compensation_df, -Root) #select all but a specific column
```

### Slice()
```{r}
slice(compensation_df, 2) #grabs a specific row
slice(compensation_df, 2:10) #grabs a bunch or rows in a row

slice(compensation_df, c(2,3,10)) #grabs specific rows
```

### Filter()
```{r}
with(compensation_df, Fruit>80) #tells if this is true or false for each data point
filter(compensation_df, Fruit >80) #outputs the data this is true for
lo_hi_fruit<- filter(compensation_df, Fruit >80 | Fruit <20) #outputs data from multiple conditions this is true for and assign to an object
lo_hi_friut
```

```{r}
head(compensation_df)
```

### Mutate()
```{r}
compensation_df <- mutate(compensation_df, logFruit = log(Fruit))
#new variable that is the log of Fruit
head(compensation_df)
```

### Arrange()
```{r}
arrange(compensation_df, Fruit)
```

### using multiple functions
```{r}
# if you want fruit production>80 and the rootstock widths only
select(filter(compensation_df, Fruit >80), Root)
```

### Piping
```{r}
compensation_df |> filter(Fruit >80) |>
  select(Root)
```

### Calculating Summary Statisitcs
```{r}
mean.fruit<- summarise(group_by(compensation_df, Grazing), meanFruit = mean(Fruit))
# with piping
compensation_df |> group_by(Grazing)|>
  summarise(meanFruit = mean(Fruit), sdFruit = sd(Fruit))
```


