---
title: "Homework-16"
format: html
---

```{r}
rm(list = ls())
library(here)
library(tidyverse)
```

```{r}
cover <- read.csv(here("Data", "donnerville_percent_cover.csv"))

```

## examine dataset
```{r}
#look at data
glimpse(cover)
summary(cover)
```

## rename column names
```{r}
cover<- cover|> rename(Cover.type= cover_type) #renamed cover_type to match other two word names'
cover
```

## Make Site, Plot type and cover_type into factor variables
```{r}
cover$Site <- as.factor(cover$Site)

cover$Plot.type <- as.factor(cover$Plot.type)

cover$Cover.type <- as.factor(cover$Cover.type)

```

## Make Date into a date variable
```{r}
cover$Date <- as.Date(cover$Date, format = "%d-%b-%y")

glimpse(cover)
```


## Determine the average percent cover by cover type (bare, bryophytes, vascular plants) for Donnerville 1.
```{r}
cover|> filter(Site == "Donnerville 1") |>
  group_by(Cover.type) |>
  summarise(average_percent_cover= mean(Percent) )
```


## Determine the average percent vascular plant cover across all sites.
```{r}
cover|> filter(Cover.type == "Vascular") |>
  summarise(average_percent_vascular = mean(Percent))
```

